"""Snakemake pipeline generator.

Generates a complete, valid Snakefile from a PipelineConfig.
Each PipelineStep becomes one Snakemake rule with proper input/output chaining,
conda environment specification, and thread/memory resource declarations.

Design notes:
- Uses PipelineConfig.execution_order() for correct DAG-aware rule ordering.
- Generates a companion config.yaml with parameterizable values.
- Per-rule conda directives use the step's conda_env if set.
- Docker/Singularity containers are emitted as singularity directives.
"""

from __future__ import annotations

import textwrap
from typing import Optional

from researcher_ai.models.pipeline import PipelineConfig, PipelineStep


class SnakemakeGenerator:
    """Generate a Snakefile from a PipelineConfig.

    Produces a valid Snakemake workflow with:
    - Rule for each PipelineStep
    - Proper input/output chaining (depends_on → input references)
    - Config file for parameters
    - Conda environment per rule (when available)
    - Resource declarations (threads, mem_mb)
    """

    def generate(self, config: PipelineConfig) -> str:
        """Generate complete Snakefile content as a string.

        Returns:
            Valid Snakefile content ready to write to disk.
        """
        ordered_ids = config.execution_order()
        step_map = {s.step_id: s for s in config.steps}
        ordered_steps = [step_map[sid] for sid in ordered_ids if sid in step_map]

        lines: list[str] = []
        lines += self._header(config)
        lines += self._configfile_block(config)
        lines += self._rule_all(config, ordered_steps)
        for step in ordered_steps:
            lines += self._rule(step)
        return "\n".join(lines) + "\n"

    # ------------------------------------------------------------------
    # Section generators
    # ------------------------------------------------------------------

    def _header(self, config: PipelineConfig) -> list[str]:
        """Generate Snakefile header with description comment and imports."""
        return [
            f'"""',
            f"Snakemake workflow: {config.name}",
            f"",
            f"{config.description}",
            f"",
            f"Generated by researcher-ai PipelineBuilder.",
            f'"""',
            f"",
            f"from snakemake.utils import min_version",
            f'min_version("7.0")',
            f"",
        ]

    def _configfile_block(self, config: PipelineConfig) -> list[str]:
        """Generate configfile reference and sample wildcard setup."""
        lines = [
            'configfile: "config.yaml"',
            "",
            "# ---------------------------------------------------------------------------",
            "# Samples",
            "# ---------------------------------------------------------------------------",
            "# Populate this list from your samplesheet or config.",
            "SAMPLES = config.get('samples', [])",
            "",
        ]
        if config.datasets:
            lines += [
                "# Datasets referenced by this pipeline:",
                "DATASETS = " + repr(config.datasets),
                "",
            ]
        return lines

    def _rule_all(
        self, config: PipelineConfig, ordered_steps: list[PipelineStep]
    ) -> list[str]:
        """Generate the 'rule all' with final target outputs.

        The final targets are the outputs of terminal steps (steps that no
        other step depends on) plus any explicit figure targets.
        """
        # Identify terminal steps: those not listed as depends_on of any other step
        all_deps: set[str] = set()
        for step in ordered_steps:
            all_deps.update(step.depends_on)

        terminal_steps = [s for s in ordered_steps if s.step_id not in all_deps]

        target_lines: list[str] = []
        for step in terminal_steps:
            for out in step.outputs:
                # Only use expand() when the output path is sample-parameterised
                if "{sample}" in out:
                    target_lines.append(f'        expand("{out}", sample=SAMPLES),')
                else:
                    target_lines.append(f'        "{out}",')
        if not target_lines:
            target_lines = ['        # Add your final output files here']

        lines = [
            "# ---------------------------------------------------------------------------",
            "# rule all: declare final targets",
            "# ---------------------------------------------------------------------------",
            "rule all:",
            "    input:",
        ]
        lines += target_lines
        lines += ["", ""]
        return lines

    def _rule(self, step: PipelineStep) -> list[str]:
        """Generate a single Snakemake rule from a PipelineStep."""
        lines: list[str] = [
            "# ---------------------------------------------------------------------------",
            f"# {step.name}",
            "# ---------------------------------------------------------------------------",
            f"rule {step.step_id}:",
        ]

        # input block — always emit both literal file inputs AND dependency references
        # so that Snakemake enforces the full depends_on DAG regardless of whether
        # explicit inputs are present (fixes mutual-exclusion bug in original code).
        has_explicit = bool(step.inputs)
        has_deps = bool(step.depends_on)
        if has_explicit or has_deps:
            lines.append("    input:")
            for i, inp in enumerate(step.inputs):
                lines.append(f'        "{inp}",')
            for dep_id in step.depends_on:
                lines.append(f"        rules.{dep_id}.output,")

        # output block
        if step.outputs:
            lines.append("    output:")
            for i, out in enumerate(step.outputs):
                sep = "," if i < len(step.outputs) - 1 else ""
                lines.append(f'        "{out}"{sep}')
        else:
            lines.append("    output:")
            lines.append(f'        "{step.step_id}_output/"')

        # params block
        if step.parameters:
            lines.append("    params:")
            for key, val in step.parameters.items():
                lines.append(f'        {key}=config.get("{key}", "{val}"),')

        # threads
        lines.append(f"    threads: {step.threads}")

        # resources
        lines.append("    resources:")
        lines.append(f"        mem_mb={step.memory_gb * 1024},")
        lines.append(f"        runtime=120,")

        # conda / container
        if step.conda_env:
            lines.append(f'    conda: "{step.conda_env}"')
        if step.container:
            lines.append(f'    singularity: "docker://{step.container}"')

        # log
        lines.append(f'    log: "logs/{step.step_id}.log"')

        # shell
        cmd = step.command.replace("{input}", "{input}").replace("{output}", "{output}")
        lines.append("    shell:")
        lines.append(f'        "{cmd} 2> {{log}}"')

        lines.append("")
        return lines
