"""Generate a plain-English inventory of all tests under tests/."""

from __future__ import annotations

import ast
from dataclasses import dataclass
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
TESTS_DIR = ROOT / "tests"
OUTPUT_PATH = ROOT / "docs" / "test_catalog.md"


@dataclass
class TestCase:
    name: str
    description: str


def _humanize(name: str) -> str:
    text = name.strip().replace("_", " ")
    text = " ".join(text.split())
    if not text:
        return "Unnamed test."
    return text[0].upper() + text[1:] + "."


def _extract_docstring_summary(node: ast.AST) -> str | None:
    doc = ast.get_docstring(node)
    if not doc:
        return None
    first = doc.strip().splitlines()[0].strip()
    if not first:
        return None
    if first.endswith("."):
        return first
    return f"{first}."


def _collect_tests_from_file(path: Path) -> list[TestCase]:
    tree = ast.parse(path.read_text(encoding="utf-8"))
    tests: list[TestCase] = []

    for node in tree.body:
        if isinstance(node, ast.FunctionDef) and node.name.startswith("test_"):
            summary = _extract_docstring_summary(node) or _humanize(node.name.removeprefix("test_"))
            tests.append(TestCase(name=node.name, description=summary))
            continue

        if isinstance(node, ast.ClassDef) and node.name.startswith("Test"):
            class_summary = _extract_docstring_summary(node) or _humanize(node.name.removeprefix("Test"))
            for child in node.body:
                if isinstance(child, ast.FunctionDef) and child.name.startswith("test_"):
                    method_summary = _extract_docstring_summary(child) or _humanize(child.name.removeprefix("test_"))
                    tests.append(
                        TestCase(
                            name=f"{node.name}.{child.name}",
                            description=f"{class_summary} {method_summary}",
                        )
                    )
    return tests


def main() -> None:
    files = sorted(TESTS_DIR.glob("test_*.py"))
    lines: list[str] = []
    lines.append("# Test Catalog")
    lines.append("")
    lines.append("This document lists every test and explains it in plain English.")
    lines.append("It is generated by `scripts/generate_test_catalog.py`.")
    lines.append("")
    lines.append(f"- Total test files cataloged: `{len(files)}`")

    total_tests = 0
    for path in files:
        tests = _collect_tests_from_file(path)
        total_tests += len(tests)

    lines.append(f"- Total tests cataloged: `{total_tests}`")
    lines.append("")

    for path in files:
        rel = path.relative_to(ROOT)
        tests = _collect_tests_from_file(path)
        lines.append(f"## `{rel}`")
        lines.append("")
        if not tests:
            lines.append("- No `test_*` functions detected in this file.")
            lines.append("")
            continue
        for tc in tests:
            lines.append(f"- `{tc.name}`: {tc.description}")
        lines.append("")

    OUTPUT_PATH.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote {OUTPUT_PATH} ({total_tests} tests)")


if __name__ == "__main__":
    main()
