"""Generate a catalog of schema formats used in the codebase."""

from __future__ import annotations

import ast
from dataclasses import dataclass
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SOURCE_ROOT = ROOT / "researcher_ai"
OUTPUT_PATH = ROOT / "docs" / "schema_formats.md"


@dataclass
class FieldDef:
    name: str
    annotation: str
    required: bool


@dataclass
class SchemaDef:
    kind: str
    name: str
    module_path: str
    fields: list[FieldDef]


def _safe_unparse(node: ast.AST | None) -> str:
    if node is None:
        return "Any"
    try:
        return ast.unparse(node)
    except Exception:
        return "Any"


def _extract_fields(class_node: ast.ClassDef) -> list[FieldDef]:
    fields: list[FieldDef] = []
    for stmt in class_node.body:
        if isinstance(stmt, ast.AnnAssign) and isinstance(stmt.target, ast.Name):
            fields.append(
                FieldDef(
                    name=stmt.target.id,
                    annotation=_safe_unparse(stmt.annotation),
                    required=stmt.value is None,
                )
            )
    return fields


def _iter_python_files() -> list[Path]:
    files = sorted(SOURCE_ROOT.rglob("*.py"))
    return [p for p in files if "__pycache__" not in p.parts]


def _base_names(node: ast.ClassDef) -> set[str]:
    names: set[str] = set()
    for base in node.bases:
        if isinstance(base, ast.Name):
            names.add(base.id)
        elif isinstance(base, ast.Attribute):
            names.add(base.attr)
    return names


def _collect_schemas(path: Path) -> list[SchemaDef]:
    tree = ast.parse(path.read_text(encoding="utf-8"))
    rel = path.relative_to(ROOT).as_posix()
    out: list[SchemaDef] = []

    for node in tree.body:
        if not isinstance(node, ast.ClassDef):
            continue
        bases = _base_names(node)
        kind: str | None = None
        if "BaseModel" in bases:
            kind = "Pydantic BaseModel"
        elif "TypedDict" in bases:
            kind = "TypedDict"
        if kind is None:
            continue
        out.append(
            SchemaDef(
                kind=kind,
                name=node.name,
                module_path=rel,
                fields=_extract_fields(node),
            )
        )
    return out


def main() -> None:
    schemas: list[SchemaDef] = []
    for path in _iter_python_files():
        schemas.extend(_collect_schemas(path))

    lines: list[str] = []
    lines.append("# Schema Formats")
    lines.append("")
    lines.append("This document catalogs schema-like types used by `researcher-ai`.")
    lines.append("It is generated by `scripts/generate_schema_catalog.py`.")
    lines.append("")
    lines.append("## Format Conventions")
    lines.append("")
    lines.append("- Primary schema format: Pydantic `BaseModel` objects serialized to JSON.")
    lines.append("- Internal orchestration state format: `TypedDict` structures (Python dict shape contracts).")
    lines.append("- Parser-side extraction schemas are prefixed with `_` and are LLM structured-output contracts.")
    lines.append("")
    lines.append(f"- Total schemas cataloged: `{len(schemas)}`")
    lines.append("")

    grouped: dict[str, list[SchemaDef]] = {}
    for schema in schemas:
        grouped.setdefault(schema.module_path, []).append(schema)

    for module_path in sorted(grouped):
        lines.append(f"## `{module_path}`")
        lines.append("")
        for schema in sorted(grouped[module_path], key=lambda s: s.name.lower()):
            lines.append(f"### `{schema.name}` ({schema.kind})")
            lines.append("")
            if not schema.fields:
                lines.append("- No annotated fields declared directly on this class.")
                lines.append("")
                continue
            lines.append("| Field | Type | Required |")
            lines.append("| --- | --- | --- |")
            for field in schema.fields:
                req = "Yes" if field.required else "No"
                lines.append(f"| `{field.name}` | `{field.annotation}` | {req} |")
            lines.append("")

    OUTPUT_PATH.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote {OUTPUT_PATH} ({len(schemas)} schemas)")


if __name__ == "__main__":
    main()
